### ISSUE TITLE
Genozip Error in lookback_get_do:70

### ISSUE THREAD

**Issue by coolkom** [divonlan/genozip#20] opened 2022-01-21 12:51 UTC
Hello,

I got this error while running genozip v13.0.9

***
Error in lookback_get_do:70: expecting lookback=329 <= lookback_len=4 for ctx=PS vb=1 line_i=14
If this is unexpected, please contact support@genozip.com.
***

I'm running the program on a slurm cluster and the command was like this : genozip  --reference ref.genozip vcf.gz
OR
genozip --threads 30 --vblock 2000 --reference ref.genozip vcf.gz
OR JUST
genozip vcf.gz

Do you have an idea what might be causing this please?

Thanks!

**Comment by divonlan** [comment] 2022-01-22 01:01
Thanks for reporting this, the issue is now fixed and released as 13.0.10.

**Closed by divonlan** 2022-01-22 01:01 UTC
