### ISSUE TITLE
FASTQ read change after genozipping

### ISSUE THREAD

**Issue by MatthewPace98** [divonlan/genozip#25] opened 2022-06-06 10:01 UTC
We have recently noticed an issue with our paired-end genozipped DNA FASTQ files, where upon genounzipping, some reads were changed. We used genozip v12.0.37 to execute the following command:
`genozip --reference Homo_sapiens_assembly38.ref.genozip --pair file_R1.fastq file_R2.fastq --threads 8`

We also used `Process` from the `multiprocessing` python library, running 8 instances of genozip simultaneously.

The two files are identical in size, with only the line containing the nucleotide sequence sporadically being changed. Here’s an extract from one of the genounzipped files:
```
+
FF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF
@A00553:69:HYL2YDSXY:4:1101:6876:1000 1:N:0:TTGGACTC+CTGCTTCC
TATGCATTTCAATACTATAGGATTCACGTTAATAGAAATAACCAGATGAAATGCTTCTGGTATGTCACCTTCCCTACCCACATAAGCCAGTGTTTTTTTCTGTGAATAACAAAAACAGCAGAATTTACTTGCCTATCCGTAAGAAGTTACC
```
And the respective original file (notice the difference is solely in the nucleotides):
```
+
FF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFF
@A00553:69:HYL2YDSXY:4:1101:6876:1000 1:N:0:TTGGACTC+CTGCTTCC
TCAGATCACAATGTATACAAATTTTTTTCCTGCTAGTTTTCTTTCACATTACTGCAATCTATCTCTTTTAAAAAAAGTATATAGTGCAGCTATTTCAGCCAGGCACGGTGGTTCATGCCTGTAATCCCAGCACTTTGGGAGGCAGAGGCGG
```
We could not reproduce this result, and we could find no errors in the log files. Do you have any suggestions for a potential cause/remedy, please?

**Comment by divonlan** [comment] 2022-06-10 10:23
Under investigation. So far, unable to reproduce.

**Comment by divonlan** [comment] 2022-06-13 01:11
Closing for now, as neither I nor the user can reproduce this, and possibly fixed in newer version.

**Closed by divonlan** 2022-06-13 01:11 UTC

**Comment by divonlan** [comment] 2022-06-27 08:27
Update: this issue doesn't replicate, it happened on a specific machine, that concurrently displayed unexplained errors of other tools. Possibly faulty hardware. I will add a another layer of validation in Genozip, to detect this (very rare) environmental issue from affecting Genozip.

**Comment by divonlan** [comment] 2022-08-22 07:50
Update: this issue is now resolved in 13.0.21. See Release Notes.
